### ISSUE TITLE
PLEASE CAMENDURU UPDATE THE SAGEMAKER REPOSITORY

### ISSUE THREAD

**Issue by DevRushi-engg** [camenduru/stable-diffusion-webui-sagemaker#3]
@camenduru I am having a lot of errors when trying to run the Sagemaker repository. I have tried to troubleshoot the issue, but I have not been able to resolve it. I would appreciate it if you could update the repository to fix the errors.

**Comment by camenduru** [comment]
check this https://github.com/etherealxx/volatile-concentration-localux-colab

**Comment by DevRushi-engg** [comment]
@camenduru really thankful of you for the link. But the the error are about the trace back files ,like script.py,lora,additional network i tried to fix it doesn't work.
